<?php

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;
use Doctrine\ORM\Mapping as ORM;
/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 */
class User extends BaseUser
{
    /**
     * @var int $id
     */
    protected $id;

    /**
     * Get id.
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @ORM\OneToMany(targetEntity="\UtExam\ProEvalBundle\Entity\Examen", mappedBy="user")
     */
    private $examen;

    /**
     * @ORM\OneToMany(targetEntity="\UtExam\ProEvalBundle\Entity\ExamenAuto", mappedBy="user")
     */
    private $examenAuto;

    /**
     * Add examen.
     *
     * @param \UtExam\ProEvalBundle\Entity\Examen $examen
     *
     * @return User
     */
    public function addExamen(\UtExam\ProEvalBundle\Entity\Examen $examen)
    {
        $this->examen[] = $examen;

        return $this;
    }

    /**
     * Remove examen.
     *
     * @param \UtExam\ProEvalBundle\Entity\Examen $examen
     *
     * @return boolean TRUE if this collection contained the specified element, FALSE otherwise.
     */
    public function removeExamen(\UtExam\ProEvalBundle\Entity\Examen $examen)
    {
        return $this->examen->removeElement($examen);
    }

    /**
     * Get examen.
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getExamen()
    {
        return $this->examen;
    }

    /**
     * Add examenAuto.
     *
     * @param \UtExam\ProEvalBundle\Entity\ExamenAuto $examenAuto
     *
     * @return User
     */
    public function addExamenAuto(\UtExam\ProEvalBundle\Entity\ExamenAuto $examenAuto)
    {
        $this->examenAuto[] = $examenAuto;

        return $this;
    }

    /**
     * Remove examenAuto.
     *
     * @param \UtExam\ProEvalBundle\Entity\ExamenAuto $examenAuto
     *
     * @return boolean TRUE if this collection contained the specified element, FALSE otherwise.
     */
    public function removeExamenAuto(\UtExam\ProEvalBundle\Entity\ExamenAuto $examenAuto)
    {
        return $this->examenAuto->removeElement($examenAuto);
    }

    /**
     * Get examenAuto.
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getExamenAuto()
    {
        return $this->examenAuto;
    }


}
